import img1 from "./src/images/img1.png";
import img2 from "./src/images/img2.jpg";
import img3 from "./src/images/img3.png";
import img4 from "./src/images/img4.png";
import img5 from "./src/images/img5.png"

export let hotel1 = [
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img5, img3, img1, img4, img2,],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img1, img3, img2,img5, img4],
    price: "3000",
    date: "25-20 May",
    title: "Hotel 3",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img4, img1, img2,img5, img3],
    price: "4500",
    date: "10-20 Oct",
    title: "Hotel 3",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img2,img5, img1, img3, img4],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img5,img1, img2, img4, img3],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img2,img5, img1, img3, img4],
    price: "3000",
    date: "25-20 May",
    title: "Hotel 3",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img4, img1, img2,img5, img3, ],
    price: "4500",
    date: "10-20 Oct",
    title: "Hotel 3",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img3, img1, img2,img5,  img4],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img2,img5, img1,  img3, img4],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img1, img2,img5, img3, img4],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img3, img1, img2,img5,  img4],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img4, img1, img2,img5, img3, ],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img1, img2,img5, img3, img4],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img3, img1, img2,img5,  img4],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [img4, img1, img2,img5, img3, ],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
  {
    rating: "4",
    desc: "Beach and Sunset Views",
    imgSrc: [ img2,img5,img1, img3, img4],
    price: "2000",
    date: "15-20 May",
    title: "Hotel 1",
  },
];
